# Generated by Django 4.2.25 on 2025-10-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='responded_at',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='response',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
