# Generated by Django 4.2.25 on 2025-10-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_remove_inquiry_responded_at_remove_inquiry_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='is_read',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
