# Generated by Django 5.1.4 on 2025-11-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='agent_location',
            field=models.CharField(blank=True, default='', help_text='Agent-provided location details for later review', max_length=500),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of bathrooms (if applicable)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, help_text='Number of bedrooms (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage_spaces',
            field=models.IntegerField(blank=True, help_text='Number of garage spaces (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.location'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lot/land size in acres', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the property', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial')], default='house', help_text='Deprecated: use Property Type model instead', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='square_feet',
            field=models.IntegerField(blank=True, help_text='Total area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='year_built',
            field=models.IntegerField(blank=True, help_text='Year property was built (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='listings.propertytype', verbose_name='Property Type'),
        ),
    ]
