# Generated by Django 5.1.4 on 2025-11-14 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_propertytype_listing_agent_location_and_more'),
    ]

    operations = [
    ]
